### ISSUE TITLE
Controller address partially copied

### ISSUE THREAD

**Issue by glihm** [cartridge-gg/controller#1013]
When opening the controller page, the copy button on a side of the address copies it with the `...` at the middle and not the actual address.

`0x048e13ef7ab79...d7e7b17bac06715`

<img width="483" alt="image" src="https://github.com/user-attachments/assets/4bcce323-f055-4966-891d-4288c7d35b5e">

**Comment by broody** [comment]
Fixed in https://github.com/cartridge-gg/controller/pull/1014
