### ISSUE TITLE
Latency when fetching ERC 20 metadata 

### ISSUE THREAD

**Issue by clicksave** [cartridge-gg/controller#1078]
Any way we can improve this?

Took about 20 seconds for the contract information to appear

Before
<img width="502" alt="image" src="https://github.com/user-attachments/assets/86f01f27-15e9-4592-8af5-93b769c44b7d">

After
<img width="475" alt="image" src="https://github.com/user-attachments/assets/b750d19b-e1e9-4d57-a00a-768714d2d610">

**Comment by JunichiSugiura** [comment]
Loading time seems reasonable at least for now
