### ISSUE TITLE
Make the header buttons more consistent

### ISSUE THREAD

**Issue by clicksave** [cartridge-gg/controller#1081]
Header buttons are different sizes and different colors. This is may have been my fault due to some inconsistencies in the mocks in a few areas. 

<img width="469" alt="image" src="https://github.com/user-attachments/assets/bc8309d4-fe7c-4940-8086-405a6f44ea74">

See below. both should be 40px tall and use bg-background. Have updated figma accordingly.

<img width="1455" alt="image" src="https://github.com/user-attachments/assets/0ec674c3-ea19-46d3-9a3b-f0c0f9c96dde">

**Comment by bal7hazar** [comment]
It seems it has been fixed already because I don't have this behavior on dopewars
![image](https://github.com/user-attachments/assets/b8e5771c-8062-4b70-a813-8349104cb1fa)

**Comment by tarrencev** [comment]
ah yes i fixed this
