### ISSUE TITLE
Update some of the language on the session details page

### ISSUE THREAD

**Issue by clicksave** [cartridge-gg/controller#1084]
"Approve **(n) methods**" is more concise than what we have currently 

<img width="659" alt="image" src="https://github.com/user-attachments/assets/32d02048-0817-4d29-8512-0479a6ecef59">

"Approve **(n) message** formats" is better as well

<img width="659" alt="image" src="https://github.com/user-attachments/assets/e04c247c-58d7-477e-add8-9566ae0f5bcd">

**Comment by JunichiSugiura** [comment]
handled by #1089
