### ISSUE TITLE
Add session key verification badge to the controller

### ISSUE THREAD

**Issue by clicksave** [cartridge-gg/controller#594]
Lets manage and surface a verified badge for session keys in the controller. Verified sessions/games should be maintained in a public github repo. people will send a PR to add their game to the verified list. Clicking on the verified badge should take you to the repo. 

Here are the designs

--- 

The verified badge appears in two places

On the log in page where it expands with the session tray

<img width="1190" alt="image" src="https://github.com/user-attachments/assets/a6cf2c9c-9683-440b-a08a-e5867e7b3352">
<img width="1007" alt="image" src="https://github.com/user-attachments/assets/bd6fecf6-2bfc-46da-a18f-4d7aacf6590a">

And on the dedicated session page (ive updated the design here to give the session details a little more room) 

<img width="1232" alt="image" src="https://github.com/user-attachments/assets/d7c42b2c-f23d-4147-8970-9dcc5c464fb7">

---

[Figma Link](https://www.figma.com/design/OSbzNkyR9UYV4Erz9oF9JJ/Controller?node-id=3692-35410&t=MvzrNy0BFfo3gzch-1)

**Comment by ponderingdemocritus** [comment]
This sounds good. Potentially we even include this check when users submit for custom styling.
