### ISSUE TITLE
Improvements to the network tag

### ISSUE THREAD

**Issue by clicksave** [cartridge-gg/controller#670]
atm the network tags are pretty hard to differentiate. the dot is not communicative enough

Lets improve them. Per @JunichiSugiura suggestion lets add a slot tag as well

<img width="708" alt="image" src="https://github.com/user-attachments/assets/573fe08f-0590-4e37-960d-b346dfd51d11">

https://www.figma.com/design/OSbzNkyR9UYV4Erz9oF9JJ/Controller?node-id=5974-11475&t=BNkHGn3BbXI9OmBG-1

---

Here's what it looks like in the controller

<img width="393" alt="image" src="https://github.com/user-attachments/assets/8ee954f3-f6ff-4426-b725-a12bcda03539">

---

Icons

[SVG Network Icons.zip](https://github.com/user-attachments/files/16919598/SVG.Network.Icons.zip)

**Comment by rsodre** [comment]
@clicksave 
would be useful to still see the actual chain id somewhere
since we can have multiple slot deployments during development

**Comment by clicksave** [comment]
> @clicksave would be useful to still see the actual chain id somewhere since we can have multiple slot deployments during development

excellent feedback, thank you!

**Comment by JunichiSugiura** [comment]
@rsodre That was the old implementation ahah. I'll undo while keeping the slot icon
