### ISSUE TITLE
Updates to the Info label

### ISSUE THREAD

**Issue by clicksave** [cartridge-gg/controller#673]
We have a specific rendering for friendly informative messages that do not require user actions, e.g. "The controller is in alpha". 

This appears on the 'Fund your account' page 

<img width="1094" alt="image" src="https://github.com/user-attachments/assets/83b05540-182f-428e-818f-0e21f712d550">

---

Component in [Figma](https://www.figma.com/design/OSbzNkyR9UYV4Erz9oF9JJ/Controller?node-id=5909-35966&t=xW0RZjhq6dpKueSJ-1)

**Comment by JunichiSugiura** [comment]
covered by #682
