### ISSUE TITLE
Controller to fetch addresses given usernames

### ISSUE THREAD

**Issue by broody** [cartridge-gg/controller#980]
Controller has `fetchControllers` to return associated controller usernames given addresses. We should support a similar API to fetch addresses given usernames

**Comment by JunichiSugiura** [comment]
Something like this? It currently assumes `username : controller === 1 : 1` tho.

https://github.com/cartridge-gg/controller/blob/f9a1f72fc3366e99f9e38b0860e036e4a16bef3f/packages/profile/src/hooks/account.ts

**Comment by broody** [comment]
Right, could probably work if we just exposed this. Was thinking making it equivalent to fetchControllers, addresses => usernames but can't really think of a usecase

Would still probably want to rate limit this too
